[package]
name = "midiedit-app"
version = "0.1.0"
authors = ["dylan"]
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["derive"]}
anyhow = "1.0.100"
log = "0.4.29"
midiedit-cli = {path = "../cli"}